name: TruffleHog OSS

on:
  workflow_dispatch:

jobs:
  scan_secrets:
    name: Scan Repository for Secrets
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install TruffleHog
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install trufflehog
    
    - name: Scan for secrets
      run: |
        trufflehog git https://github.com/rijmjada/Terraform-Sprint-2 --json --only-verified --fail > secrets_report.json

    
    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: secrets-report
        path: secrets_report.json
